[package]
name = "pwos"
version = "1.2.0"
authors = ["Fábián Varga <23280129+br0kenpixel@users.noreply.github.com>"]
description = "PixelWeatherOS for the PixelWeather weather station project."
homepage = "https://github.com/PixelWeatherProject"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/PixelWeatherProject/pwos"
edition = "2021"
resolver = "2"
rust-version = "1.77"

[[bin]]
name = "pwos"
harness = false # do not use the built in cargo test harness -> resolve rust-analyzer errors

[profile.release]
opt-level = 3

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[dependencies]
esp-idf-svc = { version = "0.49.1", default-features = false, features = [
    "std",
    "alloc",
    "binstart",
] }
simple_logger = { version = "5.0.0", default-features = false, features = [
    "colors",
    "colored",
] }
pwmp-client = { path = "../../C Projects/Rust/pwmp-new-stack/pwmp-client" }
log = { version = "0.4", default-features = false }
build-time = "0.1.3"
thiserror = "2.0.9"
heapless = "0.8.0"

[build-dependencies]
embuild = "0.32.0"
cc = "=1.1.30"     # Necessary until a new version of `esp-idf-sys` is released
